const { chromium } = require('C:/Users/farri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve('outputs/iki-portfolio.html')).href, { waitUntil:'networkidle' });
  await page.context().setOffline(true);
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('.project-card').count(),6);
  assert.equal(await page.evaluate(() => document.fonts.check('500 16px Manrope')),true);
  await page.locator('[data-filter="marketing"]').click();
  assert.equal(await page.locator('.project-card:visible').count(),3);
  await page.locator('[data-project="yamaha-content-campaign"] .project-link').click();
  assert.equal(await page.locator('#case-title').textContent(),'Yamaha Content Campaign');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#case-dialog').evaluate(d=>d.open),false);
  await page.locator('[data-filter="all"]').click();
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.waitForFunction(()=>!document.querySelector('.desktop-nav .is-active'));
  await page.screenshot({path:path.resolve('outputs/iki-preview.png')});
  await page.setViewportSize({width:390,height:844});
  await page.locator('.menu-toggle').click();
  assert.equal(await page.locator('#mobile-menu').isVisible(),true);
  await page.locator('#mobile-menu a[href="#contact"]').click();
  assert.equal(await page.locator('#mobile-menu').isVisible(),false);
  const dimensions = await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
  assert.ok(dimensions.scroll<=dimensions.width);
  await page.screenshot({path:path.resolve('work/qa/mobile-contact-final.png')});
  const network = await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>r.name.startsWith('http')).length);
  assert.equal(network,0);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({standalone:'PASS',offline:'PASS',filters:'PASS',caseStudies:'PASS',mobileMenu:'PASS',externalRequests:network,errors},null,2));
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
